### ISSUE TITLE
Demo is not working if I upgrade the versions of dependencies to the latest ones

### ISSUE THREAD

**Issue by duchiporexia** [alexstrat/graphql-field-arguments-coercion#2]
https://codesandbox.io/s/graphql-field-arguments-coercion-usage-gjppl?file=/index.ts

Currently, the demo seems not working when I use the following lib versions. I see the `visitFieldDefinition` of `FieldResoverWrapperVisitor` is not executed. So the validation is not working.

    "graphql-tools": "^6.0.12",
    "apollo-server": "^2.15.1",
    "graphql": "^15.2.0",

**Comment by alexstrat** [comment]
It's working fine for me: https://codesandbox.io/s/graphql-field-arguments-coercion-usage-cwvqn?file=/index.ts

I've used `graphql-field-arguments-coercion@1.0.2`
